get port from log
IBM/conductor-h2o-sparklingwater pull request #19
Opened 2024-03-13 13:40 UTC by krasinski

2024-03-20 21:02 UTC, mfeiman approved these changes

2024-03-20 22:15 UTC, mfeiman requested changes
The code check the H2O port only on startup and then exit - instead of existing it need to have second loop running forever (with interval) to monitor state of H2O port periodically and in case it's gone then change update state to ERROR exit only in this error case.

2024-03-21 14:21 UTC, krasinski commented
@mfeiman isn't there a loop in the script? I think I just changed the inner part

2024-03-21 20:33 UTC, mfeiman commented
@krasinski yes, you have the change in the loop but that loop is waiting only for _startup_ of H2O sever then after server is started the the monitor script goes  to exits. My understanding that the issue is also about monitoring H2O state _**after** startup_  and in case when successfully running H2O server goes down then the monitoring script is required bringing the service to ERROR state. So to implement  such enhancement you will need to add to the script a second loop in which doing the same checking H2O port periodically forever and only in case the check failed (i.e. H2O server is gone) then it updates the service's state to ERROR and exit the monitoring script.

2024-04-24 20:12 UTC, mfeiman approved these changes

2024-04-24 20:37 UTC, merged